project 'GiniPayApiLib.xcodeproj'

platform :ios, '10.2'

target 'Example' do
  use_frameworks!
  pod 'GiniPayApiLib', :path => '../', :testspecs => ['Tests']
  pod 'GiniPayApiLib/DocumentsAPI', :path => '../'
  pod 'GiniPayApiLib/Pinning', :path => '../'
end
